### ISSUE TITLE
fmap.draw(), fmap.draw(output="mpl") or fmap.draw("mpl")?

### ISSUE THREAD

**Issue by JanSchnabel** [sQUlearn/squlearn#51]

**Comment by MoritzWillmann** [comment]
I'd say `fmap.draw()` producing the text output is fine because it allows for use without installing matplotlib and pylatexenc.

Regarding producing a matplotlib plot, `fmap.draw(output="mpl")` already works. If we want to make `fmap.draw("mpl")` work, we need to pass `*args` to the qiskit routine (which then requires `feature_label`, `parameter_label` and `decompose` to be set, or do some other fancy argument handling.

Thoughts @David-Kreplin ?

**Comment by MoritzWillmann** [comment]
We could also just add `output` as an argument to our draw function and default it to `text`.

**Comment by David-Kreplin** [comment]
Done by #76
